version: "2"
services:
  apache:
    build:
      context: .
      dockerfile: Dockerfile.apache
      args:
        root: $ROOT
    image: "${DOCKER_PREFIX}_apache"
    container_name: "${DOCKER_PREFIX}_apache"
    links:
      - mysql
    ports:
      - "${HTTP_PORT}:80"
    extra_hosts:
      - "${DOMAIN}:127.0.0.1"

  mysql:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    image: "${DOCKER_PREFIX}_mysql"
    container_name: "${DOCKER_PREFIX}_mysql"
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: $MYSQL_DATABASE